server:
  port: 8888
  servlet:
   # context-path: /
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: sirs

  mvc:
    format:
      date: "yyyy-MM-dd"
      date-time: "yyyy-MM-dd HH:mm:ss"
      time: "HH:mm:ss"

  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sirs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false&useAffectedRows=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console

  thymeleaf:
    cache: false

mybatis-plus:
  type-aliases-package: com.ydxl.sirs.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
